### ISSUE TITLE
Lack of scrollbar on short sites

### ISSUE THREAD

**Issue by piotrex** [vovcacik/scrollmap#3]
Many sites are too small to fill whole width of "scrollmap" and when original scrollbar is hidden, there is harder to precisely move to specific place of site using mouse. Sublime text for example additionally shows original scrollbar near document map:
![Sublime Text](http://i.imgur.com/sorHiXA.png)

**Comment by vovcacik** [comment]
You are right, with short pages, one pixel on minimap is translated to lot more pixels on web page. It is expected behaviour but it does make scrolling by dragging harder. However most users would use mouse wheel in such cases.

It would not be easy to display scrollmap and scrollbar at once, since scrollmap **is** the scrollbar. But I could take a look at [Pointer Lock API](https://developer.mozilla.org/en-US/docs/WebAPI/Pointer_Lock), which could let me change mouse sensitivity when dragging scrollmap on short pages.
